name: "JFrog CLI Example"
on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create zip
        run: |
          zip -r -q folder.zip folder1
          ls -ltr
        
      - uses: jfrog/setup-jfrog-cli@v3
        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          JF_URL: ${{ secrets.JF_URL }}

          # JFrog Platform access token
          #JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

          # Basic authentication credentials
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}

      - name: Verify Artifactory is accessible
        run: jf rt ping

      - name: Upload to Artifactory
        run: jf rt u sample-core-service-api-1.0.2511.zip brianw-generic-local/ --detailed-summary --fail-no-op
      - name: Publish build info
        run: |          
          # Collect VCS details from git and add them to the build
          jf rt build-add-git
          # Publish build info
          jf rt bp --detailed-summary
